// The one import a creator's script sees. The composition roots are behind `@platform/engine/host`,
// so a chunk resolving this specifier never reaches the server, client or renderer.

// The primitives are IMPLEMENTED in @platform/math and re-exported here, so each creator-facing
// name resolves to exactly one type. A creator has one import; the split is internal.
export type { Vec3, Bounds, Easing } from '@platform/math';
export { clamp, lerp } from '@platform/math';

// Deterministic replacements for the Math functions every engine approximates. A SyncedScript must
// reach them through this import, since Math.* is a load-time error there. These 22 names in this
// order are pinned against @platform/math and .oxlintrc.json, so editing the block is a
// cross-package change.
export {
    sin,
    cos,
    tan,
    asin,
    acos,
    atan,
    atan2,
    sinh,
    cosh,
    tanh,
    asinh,
    acosh,
    atanh,
    exp,
    expm1,
    log,
    log1p,
    log2,
    log10,
    pow,
    cbrt,
    hypot,
} from '@platform/math';

export {
    BaseScript,
    ServerScript,
    ClientScript,
    SyncedScript,
    onStart,
    onEnd,
    onUpdate,
    onClick,
    onHoverEnter,
    onHoverExit,
    onPlayerJoin,
    onPlayerLeave,
    onEvent,
    onEventRelease,
    onEventHold,
    onCollide,
    onEnter,
    onExit,
    onPress,
    onRequest,
    serverState,
    Entity,
    Player,
    Game,
    Camera,
    HUD,
    HUDScreen,
    Asset,
    game,
    hud,
    random,
    assets,
    sound,
    music,
    sleep,
    every,
    after,
    oscillate,
    orbit,
    tween,
    request,
    StatefulWrapper,
    Countdown,
    Storage,
    Scoreboard,
    Leaderboard,
    Inventory,
    Team,
    BaseMovement,
    TopDownMovement,
    PlatformerMovement,
} from '@platform/core';

export type {
    Ctx,
    FindQuery,
    Cursor,
    InputBindings,
    ActionState,
    Collider,
    Animation,
    HUDAnchor,
    AssetKind,
    AssetRef,
    SoundHandle,
    SoundOptions,
    Random,
    Movement,
    Concurrency,
    EventPhase,
    HandlerOptions,
    HandlerDecorator,
    StateDecorator,
    Host,
    ScriptQuery,
} from '@platform/core';
